---
title: "Teste _F_ de Graybill"
output:
  html_document: default
  pdf_document: default
---

**Estatística do Teste:**

$$ F(H_{0})=\frac{(\hat{\beta}-\theta)'(Y'_{1} Y_{1})(\hat{\beta}-\theta)}{2QMRes}  \sim F_\alpha (2,n-2 \phantom{1}g.l.) $$


```{r, include = FALSE}

require(readxl)
require(ggplot2)
require(pander)

dados <- read_excel("D:/Documents/Trabalhos_Mensuracao/Scrips,Funcoes,Planilhas_automaticas/Graybill_R/graybill_dados.xlsx", sheet = "graybill")
dados$er <- round(((dados$Yj - dados$Y1)/dados$Y1)*100, 2)
fit <- lm(Yj ~ Y1, dados)

```

**Resultados do Teste:**

```{r, echo=FALSE}

ggplot(data = dados, aes(x = Y1, y = Yj)) + geom_point(aes(), size = 3) + labs(x="Valor Padrão", y="Valor Proposto", title = "Comparação \n (Método proposto e alternativo)") + geom_smooth(method="lm", colour="red") + theme(axis.title=element_text(size=12, face= "bold" ), plot.title=element_text(size=14,face="bold") ) + coord_cartesian(xlim = c(0, max(dados$Y1 + 0.3)), ylim = c(0, max(dados$Yj + 0.3)))

```

***

```{r, echo=FALSE}

FdeGraybill <- function(Y1, Yj, alpha = 0.05, Tab = 3) {
  
    fit <- lm(Yj ~ Y1)
    QMRes <- sum(residuals(fit)^2)/fit$df.residual
    beta_theta <- coef(fit) - c(0,1)
    Y1linha_Y1 <- cbind(c(length(Y1), sum(Y1)), c(sum(Y1), sum(Y1^2)))
    FH0 <- round((t(beta_theta)%*%Y1linha_Y1%*%beta_theta)/(2*QMRes),4)
   
     Ftab <- round(qf(p=alpha, df1=2, df2=fit$df.residual, lower.tail = FALSE),4)
    pvalor <- round(pf(FH0,1,fit$df.residual,lower=F),6)
   
    if(FH0 > Ftab){Resultado <- "*"}else(Resultado <- "ns")  
    if(FH0 > Ftab){Conclusao <- "Yj e estatisticamente diferente de Y1, para o alpha estabelecido"}else{Conclusao <- "Yj e estatisticamente igual a Y1, para o alpha estabelecido"}
    
    Tab_Res_Simp <-  data.frame("F_H0"    = FH0, 
                                "F_crit"  = Ftab, 
                                "P_valor" = pvalor, 
                                "Alpha"   = alpha,
                                "Teste"   = Resultado) 
    
  Tab_Res_Med <- data.frame(Resultado = rbind(mean(Y1), mean(Yj), var(Y1), var(Yj), sd(Y1), sd(Yj), length(Y1), 2, fit$df.residual, Ftab, FH0, alpha, pvalor),
                            row.names = c("Media_Y1", "Media_Yj", "Variancia_Y1", "Variancia_Yj", "Desvio_Padrao_Y1", "Desvio_Padrao_Yj", "Observacoes", "g.l.1", "g.l.2", "F_crit", "F_H0", "alpha",  "p valor") )

  aux1 <- c(round(mean(Y1),2), round(var(Y1),2), round(sd(Y1),2),  length(Y1), 2, Ftab, FH0, alpha, pvalor, Resultado, Conclusao)
  aux2 <- c(round(mean(Yj),2), round(var(Yj),2), round(sd(Yj),2), length(Yj), fit$df.residual, " ", " ", " ", " ", " ", " ")
  
  Tab_Res_Comp <- data.frame("Valor_Padrao" = aux1,
                             "Valor_Proposto" = aux2, 
                             row.names = c("Media", "Variancia", "Desvio_Padrao", "Observacoes", "g.l.", "F_Critico", "F_H0", "Alpha", "P-valor" ,"Teste", "Conclusao") )

  if(Tab==1)
    {
    return(Tab_Res_Simp)
    } 
  else if(Tab==2)
    {
      return(Tab_Res_Med)
      }
  else(return(Tab_Res_Comp))
}



aux <- FdeGraybill( Y1 = dados$Y1, Yj = dados$Yj)

pander(aux)

```

